select * from v$option where parameter = 'Partitioning';
create tablespace pin00 datafile size 1G autoextend on default storage( initial 128K next 1M pctincrease 0 ); 
create tablespace pinx00 datafile size 1G autoextend on default storage( initial 128K next 1M pctincrease 0 );
create tablespace PIN_DATA datafile size 1G autoextend on default storage( initial 128K next 1M pctincrease 0 ); 
create temporary tablespace PIN_TEMP TEMPFILE '+DATA' size 1G autoextend on;
create tablespace PDC_DATA datafile  size 1G autoextend on default storage( initial 128K next 1M pctincrease 0 ); 
create temporary tablespace PDC_TEMP TEMPFILE '+DATA' size 1G autoextend on;
create tablespace ECE_DATA datafile  size 1G autoextend on default storage( initial 128K next 1M pctincrease 0 ); 
create temporary tablespace ECE_TEMP TEMPFILE '+DATA' size 1G autoextend on; 
create tablespace ECECDR_DATA datafile size 1G autoextend on default storage( initial 128K next 1M pctincrease 0 ); 
create tablespace ECECDR_IND datafile size 1G autoextend on default storage( initial 128K next 1M pctincrease 0 );
create user PIN identified by PIN#100_user;
grant resource, connect , create synonym, create any synonym to PIN; 
alter user PIN default tablespace PIN00; 
alter user PIN temporary tablespace PIN_TEMP; 
GRANT SELECT ON V_$SESSION TO PIN; 
grant create public synonym , create synonym , drop public synonym , create view , create sequence , create table , create any index , create procedure , resource, connect, alter session, create database link to PIN; 
grant unlimited tablespace to PIN; 
ALTER USER PIN quota unlimited on PINX00; 
ALTER USER PIN quota unlimited on PIN00; 
grant execute on dbms_lock to PIN; 
grant execute on dbms_aq to PIN; 
grant execute on dbms_aqadm to PIN; 
grant select on sys.gv_$aq to PIN;
create role INTEGRATE_ROLE_SEL; 
grant create session to INTEGRATE_ROLE_SEL; 
create role INTEGRATE_ROLE_ALL; 
grant connect to INTEGRATE_ROLE_ALL; 
grant INTEGRATE_ROLE_SEL to INTEGRATE_ROLE_ALL;
CREATE USER PDC IDENTIFIED BY PIN#100_user DEFAULT TABLESPACE "PDC_DATA" TEMPORARY TABLESPACE "PDC_TEMP" ; 
Grant connect, resource to PDC; 
grant execute on dbms_lock to PDC; 
grant execute on dbms_aq to PDC; 
grant execute on dbms_aqadm to PDC; 
grant resource, connect , create synonym, create any synonym to PDC; 
Alter user PDC quota unlimited on PDC_DATA; 
grant unlimited tablespace to PDC;
CREATE USER PDCXREF IDENTIFIED BY PIN#100_user DEFAULT TABLESPACE "PDC_DATA" TEMPORARY TABLESPACE "PDC_TEMP" ; 
Grant connect, resource to PDCXREF; 
grant execute on dbms_lock to PDCXREF; 
grant execute on dbms_aq to PDCXREF; 
grant execute on dbms_aqadm to PDCXREF; 
grant resource, connect , create synonym, create any synonym to PDCXREF; 
Alter user PDCXREF quota unlimited on PDC_DATA; 
grant unlimited tablespace to PDCXREF;
create user ECE IDENTIFIED BY PIN#100_user DEFAULT TABLESPACE "ECE_DATA" TEMPORARY TABLESPACE "ECE_TEMP" ; 
grant create public synonym , create synonym , drop public synonym , create view , create sequence , create table , create any index , create procedure , resource, connect, alter session, create database link to ece; 
Alter user ECE quota unlimited on ECE_DATA; 
grant unlimited tablespace to ece; 
grant execute on dbms_lock to ece; 
grant execute on dbms_aq to ece; 
grant execute on dbms_aqadm to ece; 
grant select on sys.gv_$aq to ece;
create user bocdb IDENTIFIED BY PIN#100_user DEFAULT TABLESPACE "PIN_DATA" TEMPORARY TABLESPACE "PIN_TEMP" ;  
Alter user bocdb quota unlimited on PIN_DATA;  
grant unlimited tablespace to bocdb;  
grant connect, resource to bocdb; grant execute on dbms_lock to bocdb;  
grant execute on dbms_aq to bocdb;  
grant execute on dbms_aqadm to bocdb; 
grant select on sys.gv_$aq to bocdb; 
commit;
EXIT;