variable "tenancy_ocid" {}
variable "compute_compartment_id" {}
variable "vcn_id" {}
variable "subnet_id" {}

variable "bastion_img_id" {}
variable "application_subnet_id" {}
variable "loadbalancer_subnet_id" {}
variable "oke_subnet_id" {}
variable "kube_version" {}
variable "db_private_ip" {}
variable "db_admin_password" {}
variable "bastion_shape" {}
variable "bastion_display_name" {}
variable "api_key_path" {}
variable "nsg_app" {}
variable "nsg_oke" {}
variable "dockerServer" {}
variable "dockerUsername" {}
variable "dockerPass" {}
variable "dockeremail" {}
variable "dNamespace" {}
variable "pinpass" {}
variable "pdb_name" {}
variable "region" {}
variable "custom_rsa_key" {}
variable "fingerprint" {}
variable "pub_rsa_key_path" {}
variable "user_ocid" {}
variable "dbsubnetdomain" {}
variable "dbhostname" {}
variable "mnt_avd" {}
variable "mnt_id" {}
variable "mnt_compartment" {}
variable "app_cidr" {}
